[package]
name = "xframe"
version.workspace = true
authors = ["Emil Ernerfeldt <emil.ernerfeldt@gmail.com>"]
description = "opinionated version of the egui eframe framework"
edition.workspace = true
rust-version.workspace = true
homepage = "https://github.com/emilk/egui/tree/main/crates/eframe"
license.workspace = true
readme = "README.md"
repository = "https://github.com/emilk/egui/tree/main/crates/eframe"
categories = ["gui", "game-development"]
keywords = ["egui", "gui", "gamedev"]
include = ["../LICENSE-APACHE", "../LICENSE-MIT", "**/*.rs", "Cargo.toml", "data/icon.png"]

[package.metadata.docs.rs]
all-features = true
targets = ["x86_64-unknown-linux-gnu", "wasm32-unknown-unknown"]
rustdoc-args = ["--generate-link-to-definition"]

[lints]
workspace = true

[lib]

[features]
default = [ "default_fonts" ]

# Allow crates to choose an android-activity backend via Winit
# - It's important that most applications should not have to depend on android-activity directly, and can
#   rely on Winit to pull in a suitable version (unlike most Rust crates, any version conflicts won't link)
# - It's also important that we don't impose an android-activity backend by taking this choice away from applications.

## Enable the `game-activity` backend via `egui-winit` on Android
android-game-activity = ["egui-winit/android-game-activity"]
## Enable the `native-activity` backend via `egui-winit` on Android
android-native-activity = ["egui-winit/android-native-activity"]

## If set, egui will use `include_bytes!` to bundle some fonts.
## This feature is enabled by default, so if you plan on specifying your own fonts you may disable this feature.
default_fonts = ["egui/default_fonts"]

## Enable saving app state to disk.
persistence = ["dep:home", "egui-winit/serde", "egui/persistence", "ron", "serde"]

[dependencies]
egui = { workspace = true, default-features = false, features = ["bytemuck"] }

ahash.workspace = true
document-features.workspace = true
log.workspace = true
profiling.workspace = true
raw-window-handle.workspace = true
static_assertions.workspace = true
web-time.workspace = true

# Optional dependencies

ron = { workspace = true, optional = true, features = ["integer128"] }
serde = { workspace = true, optional = true }

# -------------------------------------------
# native:
egui-winit = { workspace = true, default-features = false, features = ["clipboard", "links"] }
winit = { workspace = true, default-features = false, features = ["rwh_06"] }
egui-wgpu = { workspace = true, features = [
  "winit",
  "capture",
] } # use wgpu with winit
pollster = { workspace = true } # needed for wgpu
wgpu = { workspace = true, default-features = false, features = ["std", "parking_lot"] }
image = { workspace = true, features = ["png"] } # Needed for app icon

# optional native:
home = { workspace = true, optional = true }


# linux:
[target.'cfg(target_os = "linux")'.dependencies]
egui-winit = { workspace = true, default-features = false, features = ["wayland"] }
egui-wgpu = { workspace = true, features = [ "wayland" ] }

# android / linux - use (wgpu) vulkan
[target.'cfg(any(target_os = "android", target_os = "linux"))'.dependencies]
wgpu = { workspace = true, default-features = false, features = ["vulkan"] }

# mac:
[target.'cfg(any(target_os = "macos"))'.dependencies]
egui-wgpu = { workspace = true, features = [ "macos-window-resize-jitter-fix" ] }
objc2.workspace = true
objc2-foundation = { workspace = true, default-features = false, features = [
  "std",
  "block2",
  "NSData",
  "NSString",
] }
objc2-app-kit = { workspace = true, default-features = false, features = [
  "std",
  "NSApplication",
  "NSImage",
  "NSMenu",
  "NSMenuItem",
  "NSResponder",
] }

# iOS / macOS - use (wgpu) metal
[target.'cfg(any(target_os = "macos", target_os = "ios"))'.dependencies]
wgpu = { workspace = true, default-features = false, features = ["metal"] }

# windows:
[target.'cfg(any(target_os = "windows"))'.dependencies]
wgpu = { workspace = true, default-features = false, features = ["dx12"] }
windows-sys = { workspace = true, features = [
  "Win32_Foundation",
  "Win32_System_Com",
  "Win32_UI_Input_KeyboardAndMouse",
  "Win32_UI_Shell",
  "Win32_UI_WindowsAndMessaging",
] }

# -------------------------------------------

# Native dev dependencies for testing
[target.'cfg(not(target_arch = "wasm32"))'.dev-dependencies]
directories.workspace = true
